### ISSUE TITLE
Four functions ideas 

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloud#1]
**CleverClean** 
- Lower case 
- No punctuations 
- etc 
**CleverLemStem**
- Lemmatization 
- Stemmer
- etc. 
**CleverStopwords** 
- a more comprehensive default English stopword list/set 
- allow customization 
**CleverWordCloud** 
- Can choose shape 
(Cloud, Micky, Earth)

**Comment by ajuliettet** [comment]
So we have finalized the ideas for the functions?

**Comment by adrianne-l** [comment]
Agreed on the four functions to achieve the purpose of CleverCloud

**Comment by Arushi282** [comment]
Yes I agree as well

**Comment by Vikiano** [comment]
Sounds good to me too
