### ISSUE TITLE
Draft Team Contract 

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloud#11]
Let's discuss team contract here!

**Comment by ajuliettet** [comment]
I think we should have one required meeting and two optional meeting time slots. What do you guys think?

**Comment by adrianne-l** [comment]
Yes, it would be good to have a required meeting early in the week to start off the week's milestone (eg. Lab on Tue 2-4pm) to assign tasks to members. Optional meetings deemed necessary along the week.

**Comment by Vikiano** [comment]
Yes, lab time on Tuesday is a good time to meet.

**Comment by Arushi282** [comment]
In the team work contract I have added Tuesday 2-4 as the day to assign tasks, Friday as a optional meeting and Saturday as the day to submit everything, does that sound good?
