### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloud#48]
I think we are good to go? Let's take a look and please post any problems/concerns here!

**Comment by adrianne-l** [comment]
Python package licence discussion: https://github.com/UBC-MDS/clevercloud/issues/46

**Comment by adrianne-l** [comment]
I think we have everything and are good for submission.

**Comment by Arushi282** [comment]
Python review request: [review](https://github.com/UBC-MDS/software-review-2022/issues/32)

**Comment by ajuliettet** [comment]
1. Repo: 
Python: https://github.com/UBC-MDS/clevercloud
2. Releases 
Python: https://github.com/UBC-MDS/clevercloud/releases/tag/v1.1.1 
3. Issues on license 
Python: https://github.com/UBC-MDS/clevercloud/issues/46
5. Python review request: https://github.com/UBC-MDS/software-review-2022/issues/32
