### ISSUE TITLE
Function1: CleverClean

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/clevercloud#7]

**Comment by Arushi282** [comment]
Hi @aimee0317, @adrianne-l, and @Vikiano 

Working on writing the cleverclean function, aside from converting text to lower case and removing punctuation, should I also preprocess the text to remove all digits?

**Comment by ajuliettet** [comment]
I think we should remove the digits because they are usually not that useful in wordcloud. What do you think?

**Comment by Arushi282** [comment]
> I think we should remove the digits because they are usually not that useful in wordcloud. What do you think?

Yes I agree as well, in most cases it would be quite arbitrary to have numbers show up in our final world cloud, okay will make changes to the documentation accordingly, thanks!
